	package net.netasystems.persistence.entities;
	// Generated 12/09/2018 08:01:23 AM by Hibernate Tools 5.2.10.Final

	import java.math.BigDecimal;
	import java.util.Date;
	import java.util.HashSet;
	import java.util.Set;
	import javax.persistence.Column;
	import javax.persistence.Entity;
	import javax.persistence.FetchType;
	import javax.persistence.Id;
	import javax.persistence.OneToMany;
	import javax.persistence.Table;
	import javax.persistence.Temporal;
	import javax.persistence.TemporalType;

	/**
	 * Area generated by hbm2java
	 * @param <SolicitanteTi>
	 */
	@Entity
	@Table(name = "AREA", schema = "EGLOBAL")
	public class Area<SolicitanteTi> implements java.io.Serializable {

		/**
		 *
		 * Tipo long
		 */
		private static final long serialVersionUID = 1L;
		private BigDecimal idarea;
		private String nombre;
		private Character estatus;
		private Date fechamodificacion;
		private BigDecimal idusuario;

		public Area() {
		}

		public Area(BigDecimal idarea) {
			this.idarea = idarea;
		}

		public Area(BigDecimal idarea, String nombre, Character estatus, Date fechamodificacion, BigDecimal idusuario) {
			this.idarea = idarea;
			this.nombre = nombre;
			this.estatus = estatus;
			this.fechamodificacion = fechamodificacion;
			this.idusuario = idusuario;

		}

		@Id
		
		@Column(name = "IDAREA", unique = true, nullable = false, precision = 22, scale = 0)
		public BigDecimal getIdarea() {
			return this.idarea;
		}

		public void setIdarea(BigDecimal idarea) {
			this.idarea = idarea;
		}

		@Column(name = "NOMBRE", length = 25)
		public String getNombre() {
			return this.nombre;
		}

		public void setNombre(String nombre) {
			this.nombre = nombre;
		}

		@Column(name = "ESTATUS", length = 1)
		public Character getEstatus() {
			return this.estatus;
		}

		public void setEstatus(Character estatus) {
			this.estatus = estatus;
		}

		@Temporal(TemporalType.DATE)
		@Column(name = "FECHAMODIFICACION", length = 7)
		public Date getFechamodificacion() {
			return this.fechamodificacion;
		}

		public void setFechamodificacion(Date fechamodificacion) {
			this.fechamodificacion = fechamodificacion;
		}

		@Column(name = "IDUSUARIO", precision = 22, scale = 0)
		public BigDecimal getIdusuario() {
			return this.idusuario;
		}

		public void setIdusuario(BigDecimal idusuario) {
			this.idusuario = idusuario;
		}

		/* (non-Javadoc)
		 * @see java.lang.Object#hashCode()
		 */
		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + ((estatus == null) ? 0 : estatus.hashCode());
			result = prime * result + ((fechamodificacion == null) ? 0 : fechamodificacion.hashCode());
			result = prime * result + ((idarea == null) ? 0 : idarea.hashCode());
			result = prime * result + ((idusuario == null) ? 0 : idusuario.hashCode());
			result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
			return result;
		}

		/* (non-Javadoc)
		 * @see java.lang.Object#equals(java.lang.Object)
		 */
		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			Area other = (Area) obj;
			if (estatus == null) {
				if (other.estatus != null)
					return false;
			} else if (!estatus.equals(other.estatus))
				return false;
			if (fechamodificacion == null) {
				if (other.fechamodificacion != null)
					return false;
			} else if (!fechamodificacion.equals(other.fechamodificacion))
				return false;
			if (idarea == null) {
				if (other.idarea != null)
					return false;
			} else if (!idarea.equals(other.idarea))
				return false;
			if (idusuario == null) {
				if (other.idusuario != null)
					return false;
			} else if (!idusuario.equals(other.idusuario))
				return false;
			if (nombre == null) {
				if (other.nombre != null)
					return false;
			} else if (!nombre.equals(other.nombre))
				return false;
			return true;
		}

		/* (non-Javadoc)
		 * @see java.lang.Object#toString()
		 */
		@Override
		public String toString() {
			return "Area [idarea=" + idarea + ", nombre=" + nombre + ", estatus=" + estatus + ", fechamodificacion="
					+ fechamodificacion + ", idusuario=" + idusuario + "]";
		}

		



}
